# Getting Connected

## Accounts
In order to gain access to the cluster, you first need an account. Contact the BLT Admins to request an account.

NOTE: Once you receive a temporary password, please reset it within 5 days of gaining access to the system.

## Getting on the network

### For Windows and OSX Users
The BLT cluster is quite isolated from LC's public-facing infrastructure. In order to connect to it, you will need a copy of the Global Protect client, which is available to LC students, faculty, and staff at [this link](https://gp.lclark.edu). Additional instructions are found [HERE](https://www.lclark.edu/live/files/25955-helpsheet-how-to-connect-to-globalprotect-vpn).

After you have installed and started the Global Protect client:

1. Start a VPN session by typing ```gp.lclark.edu``` in the text box and clicking "connect"
2. Enter your LC username and password in the two labeled text boxes. 
3. Click "connect"
Once you see the status change to "Connected" you will be able to access the cluster.

### For Linux Users
If you are using Linux to connect to the cluster, the current version of Global Protect will fail to install. Luckily, there is an open-source equivalent called OpenConnect, which installs as a menu option for debian and redhat based OSes. You will need to open your network settings and click the green plus button to add a new connection, and then select VPN when prompted. After that, enter in ```gp.lclark.edu``` for the gateway option and the same root CA certificate as you used when setting up LC secure. After you click save, it will ask for your LC id and password.

## Logging In

NOTE: In order to log in, you will need an SSH client. If you are using a Mac or Linux machine, you already have one. If you are using Windows, you will need to install PuTTY or similar.

1. Open your SSH client
  + On Mac Press the space bar and command key at the same time. then type "Terminal" and hit return
  + On Linux Open a terminal window
  + On Windows Open PuTTY
2. Log In!
  + On Mac or Linux type ```ssh <lclark username>@mayo.blt.lclark.edu``` and type your password when prompted
  + On Windows Open PuTTY, set "Host Name" to mayo.blt.lclark.edu and click "Open", and follow the prompt.
Congratulations! You have logged in to the BLT cluster! See Using the Cluster for more information about what you can do.

## Adding Files to Your Home Directory

If you want to add files to your home directory, you can use essentially any command line remote file transfer system you can think of, including rsync, scp, sftp, etc. We also have a graphical user interface on the web at (http://mayo.blt.lclark.edu/owncloud). You can log in to this service using your inital UNIX user account, but if you change your unix password, it must be manually changed separately in OwnCloud. Files that you drop to the owncloud folder "files" will go to the "files" directory in your home directory.

